name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: 'read'
  actions: 'read'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@sreeni1312'
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: git config --global user.name "sreeni"
      - run: git config --global user.email "sreeni.san1312@gmail.com"
      - run: npx lerna version --yes --conventional-commits
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: npx lerna publish from-git --yes --no-private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
      - run: npx nx print-affected --target=build
